/**
 * Plan de cuentas de DEMOSTRACIÓN: estructura de grupos del BC con subcuentas
 * genéricas. El plan real se importa del Excel con `pnpm etl coa`.
 * [código, subcuenta | null, nombre, naturaleza, clasificación, opciones]
 */
type Nature = 'DEUDORA' | 'ACREEDORA' | 'MIXTA';
type Cls = 'AC' | 'PC' | 'CC' | 'CND' | 'CNA';
interface Opts {
  currency?: string;
  reval?: string;
  intercompany?: boolean;
  pending?: boolean;
  segment?: string;
}
export type DemoAccount = [string, string | null, string, Nature, Cls, Opts?];

export const DEMO_ACCOUNTS: DemoAccount[] = [
  ['101', null, 'Efectivo en Caja', 'DEUDORA', 'AC'],
  ['101', '0001', 'Efectivo en Caja - CUP', 'DEUDORA', 'AC', { currency: 'CUP', reval: 'IC' }],
  ['101', '0002', 'Efectivo en Caja - USD', 'DEUDORA', 'AC', { currency: 'USD' }],
  ['101', '0003', 'Efectivo en Caja - EUR', 'DEUDORA', 'AC', { currency: 'EUR', reval: 'IC' }],
  ['109', null, 'Efectivo en Banco Empresarial Dominicana', 'DEUDORA', 'AC'],
  ['109', '9001', 'Banco USD - Demo Dominicana', 'DEUDORA', 'AC', { currency: 'USD' }],
  ['109', '9002', 'Banco DOP - Demo Dominicana', 'DEUDORA', 'AC', { currency: 'DOP', reval: 'ORD' }],
  ['110', null, 'Efectivo en Banco Empresarial España', 'DEUDORA', 'AC'],
  ['110', '9003', 'Banco EUR - Demo España', 'DEUDORA', 'AC', { currency: 'EUR', reval: 'IC' }],
  ['111', null, 'Efectivo en Banco Empresarial Cuba', 'DEUDORA', 'AC'],
  ['111', '9004', 'Banco CUP - Demo Cuba', 'DEUDORA', 'AC', { currency: 'CUP', reval: 'IC' }],
  ['114', null, 'Efectivo en Banco Personal Cuba', 'DEUDORA', 'AC'],
  ['114', '9005', 'Banco MLC - Socio demo', 'DEUDORA', 'AC', { currency: 'MLC', reval: 'IC' }],
  ['135', null, 'Cuenta por Cobrar a Corto Plazo Oficina', 'DEUDORA', 'AC'],
  ['135', '0001', 'CxC Oficina - Contraparte demo', 'DEUDORA', 'AC'],
  ['135', '0002', 'CxC Oficina - Contraparte demo EUR', 'DEUDORA', 'AC', { reval: 'OUE' }],
  ['146', null, 'Pagos Anticipados', 'DEUDORA', 'AC'],
  ['146', '0003', 'Pagos Anticipados Nómina', 'DEUDORA', 'AC'],
  ['136', null, 'Cuenta por Cobrar a Corto Plazo Exportación', 'DEUDORA', 'AC'],
  ['137', null, 'Cuenta por Cobrar a Corto Plazo Distribución', 'DEUDORA', 'AC'],
  ['139', null, 'Cuenta por Cobrar a Corto Plazo Inversiones', 'DEUDORA', 'AC'],
  ['180', null, 'Mercancías Exportación', 'DEUDORA', 'AC'],
  ['180', '8880', 'Mercancías Exportación - Bienes pendientes de facturar', 'DEUDORA', 'AC', { segment: '888' }],
  ['180', '8881', 'Mercancías Exportación - Servicios pendientes de facturar', 'DEUDORA', 'AC', { segment: '888' }],
  ['180', '8882', 'Mercancías Exportación - Otros costos pendientes de facturar', 'DEUDORA', 'AC', { segment: '888' }],
  ['180', '8883', 'Mercancías Exportación - Facimpex pendiente de facturar', 'DEUDORA', 'AC', { segment: '888' }],
  ['181', null, 'Mercancías Distribución', 'DEUDORA', 'AC'],
  ['181', '0001', 'Mercancías Distribución - Almacén', 'DEUDORA', 'AC', { segment: '999' }],
  ['181', '9990', 'Mercancías Distribución en almacén', 'DEUDORA', 'AC', { segment: '999' }],
  ['181', '9991', 'Mercancías Distribución en tránsito', 'DEUDORA', 'AC', { segment: '999' }],
  ['405', null, 'Cuenta por Pagar a Corto Plazo Oficina', 'ACREEDORA', 'PC'],
  ['405', '0001', 'CxP Oficina - Contraparte demo', 'ACREEDORA', 'PC'],
  ['405', '0002', 'CxP Oficina - Contraparte demo EUR', 'ACREEDORA', 'PC', { reval: 'OUE' }],
  ['406', null, 'Cuenta por Pagar a Corto Plazo Proveedores Exportación', 'ACREEDORA', 'PC'],
  ['409', null, 'Cuenta por Pagar a Corto Plazo Otros Proveedores', 'ACREEDORA', 'PC'],
  ['455', null, 'Nóminas por Pagar', 'ACREEDORA', 'PC'],
  ['410', null, 'Cuenta por Pagar a Corto Plazo Comisiones', 'ACREEDORA', 'PC'],
  ['410', '8880', 'Cuenta por Pagar a Corto Plazo Comisiones Exportación', 'ACREEDORA', 'PC', { segment: '888' }],
  ['410', '9990', 'Cuenta por Pagar a Corto Plazo Comisiones Distribución', 'ACREEDORA', 'PC', { segment: '999' }],
  ['412', null, 'Cuenta por Pagar a Corto Plazo Inversiones', 'ACREEDORA', 'PC'],
  ['480', null, 'Gastos Acumulados por Pagar', 'ACREEDORA', 'PC'],
  ['480', '9990', 'Gastos Acumulados por Pagar - Impuestos Cuba ONAT', 'ACREEDORA', 'PC', { segment: '999' }],
  ['600', null, 'Capital', 'ACREEDORA', 'CC'],
  ['600', '0001', 'Capital - Aportes de socios', 'ACREEDORA', 'CC'],
  ['630', null, 'Utilidades Retenidas', 'ACREEDORA', 'CC'],
  ['696', null, 'Operaciones entre Dependencias', 'MIXTA', 'CC', { intercompany: true }],
  ['699', null, 'Transitoria del Sistema', 'MIXTA', 'CC'],
  ['699', '0001', 'Transitoria - Banco a Banco', 'MIXTA', 'CC'],
  ['814', null, 'Costo de Ventas de Bienes', 'DEUDORA', 'CND'],
  ['814', '0001', 'Costo de Ventas de Bienes - Distribución', 'DEUDORA', 'CND', { segment: '999' }],
  ['814', '8880', 'Costo de Ventas de Bienes de Exportación', 'DEUDORA', 'CND', { segment: '888' }],
  ['814', '9990', 'Costo de Ventas de Bienes de Distribución', 'DEUDORA', 'CND', { segment: '999' }],
  ['815', null, 'Costo de Ventas de Servicios', 'DEUDORA', 'CND'],
  ['815', '8880', 'Costo de Ventas de Servicios de Exportación', 'DEUDORA', 'CND', { segment: '888' }],
  ['816', null, 'Otros Costos de Ventas', 'DEUDORA', 'CND'],
  ['816', '8880', 'Otros Costos de Ventas de Exportación', 'DEUDORA', 'CND', { segment: '888' }],
  ['817', null, 'Costos Estimados', 'DEUDORA', 'CND'],
  ['817', '8880', 'Costo Estimado de Exportación', 'DEUDORA', 'CND', { segment: '888' }],
  ['824', null, 'Comisiones de Venta', 'DEUDORA', 'CND'],
  ['824', '8880', 'Comisiones de Venta de Exportación', 'DEUDORA', 'CND', { segment: '888' }],
  ['824', '9990', 'Comisiones de Venta de Distribución', 'DEUDORA', 'CND', { segment: '999' }],
  ['826', null, 'Gastos de Operación - Salario', 'DEUDORA', 'CND'],
  ['826', '0001', 'Salario - Oficina', 'DEUDORA', 'CND'],
  ['826', '9990', 'Salario de Distribución', 'DEUDORA', 'CND', { segment: '999' }],
  ['830', null, 'Gastos de Operación - Impuestos acumulados', 'DEUDORA', 'CND'],
  ['830', '9990', 'Gastos de Operación - Impuestos acumulados Cuba ONAT Distribución', 'DEUDORA', 'CND', { segment: '999' }],
  ['837', null, 'Gastos de Operación - Alquiler', 'DEUDORA', 'CND'],
  ['837', '0001', 'Alquiler - Locales', 'DEUDORA', 'CND'],
  ['845', null, 'Gastos por Variación de Tasas de Cambio', 'DEUDORA', 'CND'],
  ['845', '0001', 'Variación TC - Cambios', 'DEUDORA', 'CND'],
  ['845', '0002', 'Variación TC - Traspasos', 'DEUDORA', 'CND'],
  ['845', '0003', 'Variación TC - Pago a Coprove', 'DEUDORA', 'CND'],
  ['846', null, 'Gastos por Tenencia', 'DEUDORA', 'CND'],
  ['846', '0001', 'Gastos por Tenencia - Efectivo', 'DEUDORA', 'CND'],
  ['846', '8880', 'Gastos por Tenencia - Cuentas por Cobrar', 'DEUDORA', 'CND'],
  ['900', null, 'Ventas de Bienes', 'ACREEDORA', 'CNA'],
  ['900', '0001', 'Ventas de Bienes - Distribución minorista', 'ACREEDORA', 'CNA', { segment: '999' }],
  ['900', '0002', 'Ventas de Bienes - Exportación', 'ACREEDORA', 'CNA', { segment: '888' }],
  ['900', '8880', 'Ventas de Bienes de Exportación - Clientes Externos', 'ACREEDORA', 'CNA', { segment: '888' }],
  ['900', '9990', 'Ventas de Bienes de Distribución Mayorista', 'ACREEDORA', 'CNA', { segment: '999' }],
  ['901', null, 'Ventas de Servicios', 'ACREEDORA', 'CNA'],
  ['901', '8880', 'Ventas de Servicios de Exportación - Clientes Externos', 'ACREEDORA', 'CNA', { segment: '888' }],
  ['924', null, 'Ingresos por Variación de Tasas de Cambio', 'ACREEDORA', 'CNA'],
  ['924', '0001', 'Variación TC - Cambios', 'ACREEDORA', 'CNA'],
  ['924', '0002', 'Variación TC - Traspasos', 'ACREEDORA', 'CNA'],
  ['925', null, 'Ingresos por Tenencia', 'ACREEDORA', 'CNA'],
  ['925', '0001', 'Ingresos por Tenencia - Efectivo', 'ACREEDORA', 'CNA'],
  ['925', '8880', 'Ingresos por Tenencia - Cuentas por Cobrar', 'ACREEDORA', 'CNA'],
  ['1900', null, 'Ventas de Bienes Internas', 'ACREEDORA', 'CNA', { intercompany: true }],
  ['1814', '8880', 'Costo de Ventas de Bienes de Exportación (internas)', 'DEUDORA', 'CND', { segment: '888' }],
  ['1815', '8880', 'Costo de Ventas de Servicios de Exportación (internas)', 'DEUDORA', 'CND', { segment: '888' }],
  ['1816', '8880', 'Otros Costos de Ventas de Exportación (internas)', 'DEUDORA', 'CND', { segment: '888' }],
  ['1817', '8880', 'Comisiones de Venta de Exportación (internas)', 'DEUDORA', 'CND', { segment: '888' }],
  ['2900', null, 'Ventas Pendientes de Exportación', 'ACREEDORA', 'CNA', { pending: true }],
  ['2814', null, 'Costo de Ventas Pendientes de Bienes de Exportación', 'DEUDORA', 'CND', { pending: true }],
  ['2815', null, 'Costo de Ventas Pendientes de Servicios de Exportación', 'DEUDORA', 'CND', { pending: true }],
  ['2816', null, 'Otros Costos de Ventas Pendientes de Exportación', 'DEUDORA', 'CND', { pending: true }],
];
